export const LS_NAME_MAP_AREA_SELECTION_HOTKEY = "MAP_AREA_SELECT_HK";
export const LS_NAME_ENTER_LEAVE_PROFILE_CREATING_MODE_HOTKEY =
  "ENTER_LEAVE_PR_CR_MODE_HK";
export const LS_NAME_DELETE_LATEST_PROFILE_HOTKEY = "DELETE_LATEST_PR_HK";

// keyCodes
const DEFAULT_MAP_AREA_SELECTION_HOTKEY = 17; // left ctrl
const DEFAULT_ENTER_LEAVE_PROFILE_CREATING_MODE_HOTKEY = "p";
const DEFAULT_DELETE_LATEST_PROFILE_HOTKEY = "d";

export const getMapAreaSelectionHotkey = () =>
  localStorage.getItem(LS_NAME_MAP_AREA_SELECTION_HOTKEY) ||
  DEFAULT_MAP_AREA_SELECTION_HOTKEY;
export const getEnterLeaveProfileCreatingModeHotkey = () =>
  localStorage.getItem(LS_NAME_ENTER_LEAVE_PROFILE_CREATING_MODE_HOTKEY) ||
  DEFAULT_ENTER_LEAVE_PROFILE_CREATING_MODE_HOTKEY;
export const getDeleteLatestProfileHotkey = () =>
  localStorage.getItem(LS_NAME_DELETE_LATEST_PROFILE_HOTKEY) ||
  DEFAULT_DELETE_LATEST_PROFILE_HOTKEY;
