export const eventsExample =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<q:quakeml xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:q="http://quakeml.org/xmlns/quakeml/1.2">\n' +
  "    <eventParameters>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-01T06:45:28.433500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3202</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3547</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>3610.0</value>\n" +
  "                    <uncertainty>316.211</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.04</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-02T00:03:08.712000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3328</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.353</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4530.0</value>\n" +
  "                    <uncertainty>640.244</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.31</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-02T08:07:32.715500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.332</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3566</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4030.0000000000005</value>\n" +
  "                    <uncertainty>647.238</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.26</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-04T10:52:51.976500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.2925</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.2957</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>3010.0</value>\n" +
  "                    <uncertainty>549.115</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.16</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-04T13:51:27.003000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3291</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3484</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4100.0</value>\n" +
  "                    <uncertainty>94.785</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.42</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-05T19:58:08.795000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3322</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3452</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4320.0</value>\n" +
  "                    <uncertainty>75.145</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.28</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-05T19:59:01.590000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3321</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3368</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4340.0</value>\n" +
  "                    <uncertainty>797.837</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.16</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-05T19:59:21.513000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3322</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3458</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4330.0</value>\n" +
  "                    <uncertainty>943.926</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.23</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-06T04:32:31.764000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3332</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3605</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4070.0000000000005</value>\n" +
  "                    <uncertainty>432.638</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.02</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-06T07:57:00.455000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3323</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3452</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4330.0</value>\n" +
  "                    <uncertainty>497.717</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.68</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-08T04:51:37.327500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3315</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3443</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4460.0</value>\n" +
  "                    <uncertainty>37.59</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.29</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-08T07:07:04.768500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3248</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3171</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4070.0000000000005</value>\n" +
  "                    <uncertainty>703.694</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.33</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-08T09:33:06.665000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3326</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3613</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4400.0</value>\n" +
  "                    <uncertainty>263.675</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.09</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-08T19:01:07.036500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3095</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3435</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>3800.0</value>\n" +
  "                    <uncertainty>133.37</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.04</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-10T11:17:23.491000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3316</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3538</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4050.0</value>\n" +
  "                    <uncertainty>484.671</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.3</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-10T19:49:32.810500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3073</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3405</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4040.0</value>\n" +
  "                    <uncertainty>172.648</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.32</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-10T23:08:14.018000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3073</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3381</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4040.0</value>\n" +
  "                    <uncertainty>90.14</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.4</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-11T08:47:57.832500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3342</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3505</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4040.0</value>\n" +
  "                    <uncertainty>18.604</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.17</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-11T09:19:01.489000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3432</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.335</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4080.0</value>\n" +
  "                    <uncertainty>332.92</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.31</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-11T10:05:00.210500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.329</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3459</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4380.0</value>\n" +
  "                    <uncertainty>786.143</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.11</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-11T11:22:26.376500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3086</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3407</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>2790.0</value>\n" +
  "                    <uncertainty>364.255</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.35</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-12T09:13:28.669000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3183</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3404</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4220.0</value>\n" +
  "                    <uncertainty>346.238</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.43</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-12T09:49:34.282000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.332</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3464</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4450.0</value>\n" +
  "                    <uncertainty>802.005</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.13</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-12T15:54:41.219500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3343</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3145</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>3640.0</value>\n" +
  "                    <uncertainty>735.608</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.19</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-12T17:16:33.585000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3309</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3559</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4010.0</value>\n" +
  "                    <uncertainty>909.972</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.0</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-13T08:37:49.943500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3315</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3459</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4440.0</value>\n" +
  "                    <uncertainty>990.922</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.11</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-14T08:06:54.815000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3087</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3558</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>3610.0</value>\n" +
  "                    <uncertainty>902.354</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.13</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-15T06:51:55.699500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.335</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3346</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4059.9999999999995</value>\n" +
  "                    <uncertainty>594.11</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.02</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-16T01:25:56.923500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3298</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3441</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4360.0</value>\n" +
  "                    <uncertainty>914.921</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.03</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-16T05:01:29.961500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3185</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3652</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4059.9999999999995</value>\n" +
  "                    <uncertainty>902.713</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.05</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-16T08:13:14.600500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3358</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3365</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4010.0</value>\n" +
  "                    <uncertainty>26.209</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.47</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-16T21:01:37.453000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3367</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.1834</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>8470.0</value>\n" +
  "                    <uncertainty>254.919</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.42</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-17T15:39:16.710000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3297</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3451</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4440.0</value>\n" +
  "                    <uncertainty>727.728</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.17</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-18T22:21:51.414000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3125</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3531</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4010.0</value>\n" +
  "                    <uncertainty>265.943</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.22</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-19T04:57:40.635500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3309</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3427</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4440.0</value>\n" +
  "                    <uncertainty>474.297</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.17</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-19T05:21:43.823500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3309</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3427</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4450.0</value>\n" +
  "                    <uncertainty>125.682</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.11</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-19T19:45:38.709500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.2555</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.388</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>7240.0</value>\n" +
  "                    <uncertainty>161.642</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.39</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-19T22:59:51.203500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.2883</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.2584</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>5860.0</value>\n" +
  "                    <uncertainty>503.876</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.51</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-21T01:42:05.519500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3192</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3052</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>5150.0</value>\n" +
  "                    <uncertainty>107.517</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.29</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-21T08:37:54.850000</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3191</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3081</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4490.0</value>\n" +
  "                    <uncertainty>831.893</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.12</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-21T15:23:41.534500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3309</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3498</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4470.0</value>\n" +
  "                    <uncertainty>633.61</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>-0.26</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "\n" +
  "        <event>\n" +
  "            <type>earthquake</type>\n" +
  "            <origin>\n" +
  "                <time>\n" +
  "                    <value>2021-01-21T15:48:50.713500</value>\n" +
  "                </time>\n" +
  "                <latitude>\n" +
  "                    <value>51.3361</value>\n" +
  "                </latitude>\n" +
  "                <longitude>\n" +
  "                    <value>53.3377</value>\n" +
  "                </longitude>\n" +
  "                <depth>\n" +
  "                    <value>4070.0000000000005</value>\n" +
  "                    <uncertainty>524.574</uncertainty>\n" +
  "                </depth>\n" +
  "            </origin>\n" +
  "            <magnitude>\n" +
  "                <mag>\n" +
  "                    <value>0.04</value>\n" +
  "                </mag>\n" +
  "                <type>mb</type>\n" +
  "            </magnitude>\n" +
  "        </event>\n" +
  "</eventParameters>\n" +
  "</q:quakeml>";
